# Generated by Django 3.2.3 on 2021-05-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_goods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
