# Generated by Django 3.2.3 on 2021-05-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210522_1222'),
        ('blog', '0006_alter_goods_image'),
    ]

    operations = [
    ]
